---
- name: Configura Jenkins master
  hosts: jenkins_master
  vars_prompt:
    - name: cluster_name
    - name: certificate
    - name: endpoint
    - name: token
  tasks:
    # Configura o repositorio do jenkins
    - name: Add Jenkins Repository
      become: true
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    # Roda upgrade do sistema
    - name: Upgrade system
      become: true
      ansible.builtin.dnf:
        update_only: true

    # Instala o jenkins
    - name: Install Jenkins
      become: true
      ansible.builtin.yum:
        pkg:
          - java-17-amazon-corretto
          - jenkins

    # Instala o Git
    - name: Install Git
      become: true
      ansible.builtin.yum:
        name: git

    # Instala o docker
    - name: Install Docker
      become: true
      ansible.builtin.yum:
        name: docker

    # Adiciona os usuarios ao groupo docker
    - name: Add docker group to Jenkins
      become: true
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: true

    # Adiciona os usuarios ao groupo docker
    - name: Add docker group to ec2-user
      become: true
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: true

    # Habilita e inicia o serviço
    - name: Start Docker Service
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # Habilita e inicia o serviço
    - name: Start Jenkins Service
      become: true
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true

    # Le Secret
    - name: Read Secret
      become: true
      ignore_errors: true
      register: secret_output
      ansible.builtin.command:
        cmd: cat /var/lib/jenkins/secrets/initialAdminPassword
        creates: /var/lib/jenkins/config_secret

    # Imprime o secret
    - name: Print Secret
      ansible.builtin.debug:
        var: secret_output.stdout_lines

    # Configura o repositorio do Kubernetes
    - name: Add Kubernetes Repository
      become: true
      ansible.builtin.yum_repository:
        name: Kubernetes
        description: Kubernetes Repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key

    # Instala kubectl
    - name: Install kubectl
      become: true
      ansible.builtin.yum:
        pkg: kubectl

    # Criar diretorio de configuração do kubectl
    - name: Create kubectl config folder
      become: true
      ansible.builtin.file:
        path: /home/ec2-user/.kube
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0744'

    # Configura Kubectl ec2-user
    - name: Configure kubectl ec2-user
      ansible.builtin.template:
        src: templates/kube_config.j2
        dest: /home/ec2-user/.kube/config
        owner: ec2-user
        group: ec2-user
        mode: '0744'

    # Criar diretorio de configuração do kubectl
    - name: Create kubectl config folder
      become: true
      ansible.builtin.file:
        path: /var/lib/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0744'

    # Configura Kubectl jenkins
    - name: Configure kubectl jenkins
      become: true
      ansible.builtin.template:
        src: templates/kube_config.j2
        dest: /var/lib/jenkins/.kube/config
        owner: jenkins
        group: jenkins
        mode: '0744'
